In [1]:
import random

# Constants
PLAYER = 'X'  # Human
AI = 'O'      # System
EMPTY = '-'

# Initialize board
def create_board():
    return [[EMPTY for _ in range(3)] for _ in range(3)]
   
# Display board
def print_board(board):
    for row in board:
        print(' '.join(row))
    print()

# Check for winner
def check_winner(board):
    lines = []
    lines.extend(board)
    lines.extend([[board[r][c] for r in range(3)] for c in range(3)])
    lines.append([board[i][i] for i in range(3)])
    lines.append([board[i][2 - i] for i in range(3)])
    for line in lines:
        if line.count(line[0]) == 3 and line[0] != EMPTY:
            return line[0]
    return None

def is_full(board):
    return all(cell != EMPTY for row in board for cell in row)
   
# Minimax algorithm
def minimax(board, depth, is_maximizing):
    winner = check_winner(board)
    if winner == AI:
        return 10 - depth
    elif winner == PLAYER:
        return depth - 10
    elif is_full(board):
        return 0
    if is_maximizing:
        best_score = float('-inf')
        for r in range(3):
            for c in range(3):
                if board[r][c] == EMPTY:
                    board[r][c] = AI
                    score = minimax(board, depth + 1, False)
                    board[r][c] = EMPTY
                    best_score = max(score, best_score)
        return best_score
    else:
        best_score = float('inf')
        for r in range(3):
            for c in range(3):
                if board[r][c] == EMPTY:
                    board[r][c] = PLAYER
                    score = minimax(board, depth + 1, True)
                    board[r][c] = EMPTY
                    best_score = min(score, best_score)
        return best_score

# Best move for AI
def best_move(board):
    best_score = float('-inf')
    move = None
    for r in range(3):
        for c in range(3):
            if board[r][c] == EMPTY:
                board[r][c] = AI
                score = minimax(board, 0, False)
                board[r][c] = EMPTY
                if score > best_score:
                    best_score = score
                    move = (r, c)
    return move

# User move
def user_move(board):
    while True:
        try:
            r, c = map(int, input("Enter row and column (0-2): ").split())
            if board[r][c] == EMPTY:
                return r, c
            else:
                print("Cell already taken.")
        except:
            print("Invalid input.")

# System random move (for system vs system)
def random_move(board, symbol):
    empty_cells = [(r, c) for r in range(3) for c in range(3) if board[r][c] == EMPTY]
    return random.choice(empty_cells)

# Game loop
def play_game(mode):
    board = create_board()
    print_board(board)
    current = PLAYER if mode == 'user_vs_system' else AI
    while True:
        if mode == 'user_vs_user':
            print(f"{current}'s turn")
            r, c = user_move(board)
        elif mode == 'user_vs_system':
            if current == PLAYER:
                print("Your turn")
                r, c = user_move(board)
            else:
                print("System's turn")
                r, c = best_move(board)
        elif mode == 'system_vs_system':
            print(f"{current}'s turn")
            r, c = best_move(board) if current == AI else random_move(board, PLAYER)
        board[r][c] = current
        print_board(board)
        winner = check_winner(board)
        if winner:
            print(f"{winner} wins!")
            break
        elif is_full(board):
            print("It's a draw!")
            break
        current = AI if current == PLAYER else PLAYER

# Choose mode
def main():
    print("Choose mode:")
    print("1. User vs System")
    print("2. System vs System")
    print("3. User vs User")
    choice = input("Enter choice (1-3): ")
    if choice == '1':
        play_game('user_vs_system')
    elif choice == '2':
        play_game('system_vs_system')
    elif choice == '3':
        play_game('user_vs_user')
    else:
        print("Invalid choice.")
main()

Choose mode:
1. User vs System
2. System vs System
3. User vs User


Enter choice (1-3):  2


- - -
- - -
- - -

O's turn
O - -
- - -
- - -

X's turn
O X -
- - -
- - -

O's turn
O X -
O - -
- - -

X's turn
O X -
O - -
X - -

O's turn
O X -
O O -
X - -

X's turn
O X -
O O -
X - X

O's turn
O X -
O O O
X - X

O wins!


In [2]:
if True:
    import numpy as np

    class VacuumCleanerAgent:
        def __init__(self, grid, garbage_positions, start_pos):
            self.grid = grid
            self.garbage_positions = set(garbage_positions)
            self.pos = start_pos
            self.cleaned = []

        def get_next_target(self):
            current_val = self.grid[self.pos]
            min_diff = float('inf')
            target = None

            for gp in self.garbage_positions:
                if gp not in self.cleaned:
                    diff = abs(current_val - self.grid[gp])
                    if diff < min_diff:
                        min_diff = diff
                        target = gp
            return target

        def move_to(self, target):
            print(f"Moving from {self.pos} to {target}")
            self.pos = target

        def clean(self):
            print(f"Cleaning cell {self.pos} with garbage {self.grid[self.pos]}")
            self.grid[self.pos] = 0
            self.cleaned.append(self.pos)

        def run(self):
            while True:
                target = self.get_next_target()
                if not target:
                    print("All garbage cleaned!")
                    break
                self.move_to(target)
                self.clean()

    # Example setup
    n, m = 5, 5
    grid = np.random.randint(1, 10, size=(n, m))
    garbage_positions = [(0, 1), (2, 3), (4, 4), (1, 2)]
    start_pos = (0, 0)

    agent = VacuumCleanerAgent(grid, garbage_positions, start_pos)
    print("Initial Grid:\n", grid)
    agent.run()
    print("Final Grid:\n", grid)

Initial Grid:
 [[5 2 8 3 1]
 [8 1 1 7 3]
 [2 6 1 4 8]
 [6 7 3 8 1]
 [3 3 2 7 2]]
Moving from (0, 0) to (2, 3)
Cleaning cell (2, 3) with garbage 4
Moving from (2, 3) to (1, 2)
Cleaning cell (1, 2) with garbage 1
Moving from (1, 2) to (0, 1)
Cleaning cell (0, 1) with garbage 2
Moving from (0, 1) to (4, 4)
Cleaning cell (4, 4) with garbage 2
All garbage cleaned!
Final Grid:
 [[5 0 8 3 1]
 [8 1 0 7 3]
 [2 6 1 0 8]
 [6 7 3 8 1]
 [3 3 2 7 0]]
